require("spec.spec_helper")

describe("parse_melody", function()
  before_each(function()
    gregosheet.init_codes()
  end)

  it("groups consecutive notes", function()
    local tokens = gregosheet.parse_melody("123")
    assert.are.equal(1, #tokens)
    assert.are.equal("note", tokens[1].type)
    assert.are.equal("123", tokens[1].glyph)
  end)

  it("separates notes and delimiters", function()
    local tokens = gregosheet.parse_melody("12-34")
    assert.are.equal(3, #tokens)
    assert.are.equal("note", tokens[1].type)
    assert.are.equal("delimiter", tokens[2].type)
    assert.are.equal("note", tokens[3].type)
  end)

  it("groups ¨ as part of notes", function()
    local tokens = gregosheet.parse_melody("12¨3")
    assert.are.equal(1, #tokens)
    assert.are.equal("note", tokens[1].type)
    assert.are.equal("12¨3", tokens[1].glyph)
  end)

  it("recognizes double barlines", function()
    local tokens = gregosheet.parse_melody("-?,-")
    assert.are.equal(3, #tokens)
    assert.are.equal("barline", tokens[2].type)
    assert.are.equal("?,", tokens[2].glyph)
  end)
end)

describe("parse_lyrics", function()
  it("splits on hyphens", function()
    local syls = gregosheet.parse_lyrics("Do-mi-nus")
    assert.are.equal(3, #syls)
    assert.are.equal("Do", syls[1].text)
    assert.is_false(syls[1].word_end)
    assert.are.equal("mi", syls[2].text)
    assert.is_false(syls[2].word_end)
    assert.are.equal("nus", syls[3].text)
    assert.is_true(syls[3].word_end)
  end)

  it("splits on spaces as word boundaries", function()
    local syls = gregosheet.parse_lyrics("a b")
    assert.are.equal(2, #syls)
    assert.is_true(syls[1].word_end)
    assert.is_true(syls[2].word_end)
  end)

  it("handles comments in angle brackets", function()
    local syls = gregosheet.parse_lyrics("<T.P.> Al-le-lu-ja!")
    assert.are.equal(5, #syls)
    assert.is_true(syls[1].comment)
    assert.are.equal("T.P.", syls[1].text)
  end)

  it("handles @ as empty syllable", function()
    local syls = gregosheet.parse_lyrics("a-@-b")
    assert.are.equal(3, #syls)
    assert.are.equal("", syls[2].text)
  end)

  it("replaces _ with space", function()
    local syls = gregosheet.parse_lyrics("in_te")
    assert.are.equal(1, #syls)
    assert.are.equal("in te", syls[1].text)
  end)
end)
